-- GENERADO por generar-baseline.mjs desde el catálogo real de producción (2026-09-21). NO editar a mano.
-- Políticas RLS de public y storage.objects. Requiere las funciones del source-sync ya aplicadas.

CREATE POLICY "abonos_crea" ON public."abonos" AS PERMISSIVE FOR INSERT TO public WITH CHECK (puede_cobrar());
CREATE POLICY "abonos_lee" ON public."abonos" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "auditoria_admin_lee" ON public."auditoria" AS PERMISSIVE FOR SELECT TO public USING (es_admin());
CREATE POLICY "auditoria_crea" ON public."auditoria" AS PERMISSIVE FOR INSERT TO public WITH CHECK (es_equipo());
CREATE POLICY "caja_admin_borra" ON public."caja_movimientos" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "caja_admin_edita" ON public."caja_movimientos" AS PERMISSIVE FOR UPDATE TO public USING (es_admin()) WITH CHECK (es_admin());
CREATE POLICY "caja_crea" ON public."caja_movimientos" AS PERMISSIVE FOR INSERT TO public WITH CHECK (puede_cobrar());
CREATE POLICY "caja_lee" ON public."caja_movimientos" AS PERMISSIVE FOR SELECT TO public USING (puede_cobrar());
CREATE POLICY "categorias_admin" ON public."categorias_inv" AS PERMISSIVE FOR ALL TO public USING (es_admin()) WITH CHECK (es_admin());
CREATE POLICY "categorias_lee" ON public."categorias_inv" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "citas_admin_borra" ON public."citas" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "citas_crea" ON public."citas" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (ve_todo_el_taller());
CREATE POLICY "citas_edita" ON public."citas" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (ve_todo_el_taller()) WITH CHECK (ve_todo_el_taller());
CREATE POLICY "citas_lee" ON public."citas" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((ve_todo_el_taller() OR (es_mecanico_activo() AND (mecanico_id = auth.uid()))));
CREATE POLICY "clientes_admin_borra" ON public."clientes" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "clientes_crea" ON public."clientes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (ve_todo_el_taller());
CREATE POLICY "clientes_edita" ON public."clientes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (ve_todo_el_taller()) WITH CHECK (ve_todo_el_taller());
CREATE POLICY "clientes_lee" ON public."clientes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((ve_todo_el_taller() OR mi_cliente(id)));
CREATE POLICY "cotizacion_items_admin_borra" ON public."cotizacion_items" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "cotizacion_items_crea" ON public."cotizacion_items" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (ve_todo_el_taller());
CREATE POLICY "cotizacion_items_edita" ON public."cotizacion_items" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (ve_todo_el_taller()) WITH CHECK (ve_todo_el_taller());
CREATE POLICY "cotizacion_items_lee" ON public."cotizacion_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "cotizaciones_admin_borra" ON public."cotizaciones" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "cotizaciones_crea" ON public."cotizaciones" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (ve_todo_el_taller());
CREATE POLICY "cotizaciones_edita" ON public."cotizaciones" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (ve_todo_el_taller()) WITH CHECK (ve_todo_el_taller());
CREATE POLICY "cotizaciones_lee" ON public."cotizaciones" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "credito_items_crea" ON public."credito_items" AS PERMISSIVE FOR INSERT TO public WITH CHECK (puede_cobrar());
CREATE POLICY "credito_items_lee" ON public."credito_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "creditos_admin_borra" ON public."creditos" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "creditos_crea" ON public."creditos" AS PERMISSIVE FOR INSERT TO public WITH CHECK (puede_cobrar());
CREATE POLICY "creditos_edita" ON public."creditos" AS PERMISSIVE FOR UPDATE TO public USING (puede_cobrar()) WITH CHECK (puede_cobrar());
CREATE POLICY "creditos_lee" ON public."creditos" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "inventario_admin" ON public."inventario" AS PERMISSIVE FOR ALL TO public USING (es_admin()) WITH CHECK (es_admin());
CREATE POLICY "inventario_lee" ON public."inventario" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "motos_admin_borra" ON public."motos" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "motos_crea" ON public."motos" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (ve_todo_el_taller());
CREATE POLICY "motos_edita" ON public."motos" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (ve_todo_el_taller()) WITH CHECK (ve_todo_el_taller());
CREATE POLICY "motos_lee" ON public."motos" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((ve_todo_el_taller() OR mi_moto(id)));
CREATE POLICY "orden_items_admin_borra" ON public."orden_items" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "orden_items_crea" ON public."orden_items" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (ve_todo_el_taller());
CREATE POLICY "orden_items_edita" ON public."orden_items" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (ve_todo_el_taller()) WITH CHECK (ve_todo_el_taller());
CREATE POLICY "orden_items_lee" ON public."orden_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "ordenes_admin_borra" ON public."ordenes" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "ordenes_crea" ON public."ordenes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (ve_todo_el_taller());
CREATE POLICY "ordenes_edita" ON public."ordenes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((ve_todo_el_taller() OR (es_mecanico_activo() AND (mecanico_id = auth.uid())))) WITH CHECK ((ve_todo_el_taller() OR (es_mecanico_activo() AND (mecanico_id = auth.uid()))));
CREATE POLICY "ordenes_lee" ON public."ordenes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((ve_todo_el_taller() OR (es_mecanico_activo() AND (mecanico_id = auth.uid()))));
CREATE POLICY "perfil_admin" ON public."perfiles" AS PERMISSIVE FOR ALL TO public USING (es_admin()) WITH CHECK (es_admin());
CREATE POLICY "perfil_propio" ON public."perfiles" AS PERMISSIVE FOR SELECT TO public USING (((id = auth.uid()) OR es_admin()));
CREATE POLICY "perfiles_admin" ON public."perfiles" AS PERMISSIVE FOR ALL TO "authenticated" USING (es_admin()) WITH CHECK (es_admin());
CREATE POLICY "perfiles_usuario_propio" ON public."perfiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((id = auth.uid()));
CREATE POLICY "venta_items_crea" ON public."venta_items" AS PERMISSIVE FOR INSERT TO public WITH CHECK (puede_cobrar());
CREATE POLICY "venta_items_lee" ON public."venta_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "ventas_admin_borra" ON public."ventas" AS PERMISSIVE FOR DELETE TO public USING (es_admin());
CREATE POLICY "ventas_admin_edita" ON public."ventas" AS PERMISSIVE FOR UPDATE TO public USING (es_admin()) WITH CHECK (es_admin());
CREATE POLICY "ventas_cobra" ON public."ventas" AS PERMISSIVE FOR INSERT TO public WITH CHECK (puede_cobrar());
CREATE POLICY "ventas_lee" ON public."ventas" AS PERMISSIVE FOR SELECT TO "authenticated" USING (ve_todo_el_taller());
CREATE POLICY "cms_admin" ON public."web_cms" AS PERMISSIVE FOR ALL TO public USING (es_admin()) WITH CHECK (es_admin());
CREATE POLICY "cms_lee" ON public."web_cms" AS PERMISSIVE FOR SELECT TO public USING (es_equipo());
CREATE POLICY "taller_borra_media" ON storage."objects" AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = 'entimotors-taller'::text) AND es_admin()));
CREATE POLICY "taller_lee_media" ON storage."objects" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((bucket_id = 'entimotors-taller'::text) AND ve_todo_el_taller()));
CREATE POLICY "taller_sube_media" ON storage."objects" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (((bucket_id = 'entimotors-taller'::text) AND ve_todo_el_taller()));
